CREATE TABLE TRANSACTIONS (
    TRANSACTION_ID VARCHAR2(100),
    SENDER_ID VARCHAR2(50) NOT NULL,
    RECEIVER_ID VARCHAR2(50) NOT NULL,
    AMOUNT NUMBER(7, 2) NOT NULL,
    CORRELATION_ID VARCHAR2(100) NOT NULL,
    ISSUED_AT DATE NOT NULL,
    RESULT VARCHAR2(15) NOT NULL,
    CONSTRAINT TRANSACTION_PK PRIMARY KEY (TRANSACTION_ID)
);